// SPDX-FileCopyrightText: Copyright 2023 Savi
// SPDX-License-Identifier: GPL-3.0-only 

import { Button, GroupBox, SpinBox, ComboBox, CheckBox, LineEdit, TabWidget, VerticalBox, HorizontalBox, Slider, SpinBox } from "std-widgets.slint";
import { Page } from "page.slint";

export component SettingsPage inherits Page{
    title: "Settings";
    description: "This page shows the input and output audio devices, and allows the user to change them.";
    GroupBox{
        
    }

}