// SPDX-FileCopyrightText: Copyright 2023 Savi
// SPDX-License-Identifier: GPL-3.0-only 

import { CheckBox, StandardListView, StyleMetrics } from "std-widgets.slint";
import { AboutPage, ConnectionPage, SettingsPage } from "./ui/pages/pages.slint";
import { SideBar } from "./ui/side_bar.slint";

import { PeerList, Signaling, SelfPeer, AudioDevices } from "globals.slint";
export { PeerList, Signaling, SelfPeer, AudioDevices }

export component App inherits Window {
    in-out property  <int> input_intensity;
    preferred-width: 700px;
    preferred-height: 300px;
    title: "Savi p2p";

    HorizontalLayout {  
        side-bar := SideBar {  
            title: "Savi";
            model: ["Connection", "Settings", "About"];
            clicked(idx) => {
                AudioDevices.on-settings = (side-bar.current-item == 1);
                if (side-bar.current-item == 1) {
                    AudioDevices.in-settings();
                }
            }
        }

        if(side-bar.current-item == 0) : ConnectionPage {}
        if(side-bar.current-item == 1) : SettingsPage {
            intensity <=> input_intensity;
        }
        if(side-bar.current-item == 2) : AboutPage {}



    }
}
