// SPDX-FileCopyrightText: Copyright 2023 Savi
// SPDX-License-Identifier: GPL-3.0-only 

// used by the gui to display the peers
export struct Peer{
    id: int,
    name: string,
    ip: string,
}

export global AudioDevices{
    in property <[string]> capture_devices;
    in property <[string]> playback_devices;
    in-out property  <int> input_intensity;
    in property <int> input_threshold;
    in property <bool> on-settings;
    callback set-capture(int);
    callback set-playback(string);
    callback set-bitrate(string);
    callback in-settings();
}

export global SelfPeer{
    in property <string> name;
    in property <string> public-ip: "127.0.0.1 / [::1]";
}

export global Signaling{
    callback create();
    callback connect(string, string);
    in property <string> address;
    in property <string> key;
    in property <bool> hosting: false;
    in property <bool> connected: false;
}

export global PeerList{
    callback connect(string);
    callback drop(int);
    callback change-volume(int, int);
    callback mute-peer(int, bool);

    in property <[Peer]> peers: [
        {id: 0, name: "Dummy", ip: "localhost" },
        {id: 1, name: "Dummy", ip: "127.0.0.1"},
    ];
}
